// MCrux.idl : IDL source for MCrux
//

// This file will be processed by the MIDL tool to
// produce the type library (MCrux.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "IMCrux.idl"

[
	uuid(D29B854E-E5BE-4222-BC23-50212F0B5F6A),
	version(1.0),
	helpstring("MCrux 1.0 Type Library")
]
library MCruxLib
{
	importlib("stdole2.tlb");
	[
		uuid(B49DE22E-A99F-4d68-BDAC-2939050BDAD4),
		helpstring("MCruxObject Class")
	]
	coclass MCruxObject
	{
		[default] interface IMCrux;
	};
};
