// FileSystem.idl : IDL source for FileSystem
//

// This file will be processed by the MIDL tool to
// produce the type library (FileSystem.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(58B04FFB-16FE-441B-A158-BDC6A166F44A),
	version(1.0),
	helpstring("FileSystem 1.0 Type Library")
]
library FileSystemLib
{
	importlib("stdole2.tlb");
	importlib("MCrux.dll");

	[
		uuid(DE6DCA18-24AA-4faa-9B50-BD074F169EA9),
		helpstring("FileSystemPlugin class")
	]
	coclass FileSystemPlugin
	{
		[default] interface IMCruxPlugin;
	};
};
