// DemoPlugin.idl : IDL source for DemoPlugin
//

// This file will be processed by the MIDL tool to
// produce the type library (DemoPlugin.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(0E165CA1-8FD4-4559-8BF5-BB86C1049A3B),
	version(1.0),
	helpstring("DemoPlugin 1.0 Type Library")
]
library DemoPluginLib
{
	importlib("stdole2.tlb");
};
